import Link from 'next/link';
import { notFound } from 'next/navigation';
import { MarketChart } from '@/components/MarketChart';
import { PrintButton } from '@/components/PrintButton';
import { getStockReport, type Row } from '@/lib/stock-data';

export const dynamic = 'force-dynamic';
const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const num = new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 });
const n = (v: unknown) => Number(v ?? 0), s = (v: unknown) => String(v ?? '—');

export default async function DailyReportPage({ params }: { params: Promise<{ date: string }> }) {
  const { date } = await params;
  const report = await getStockReport(date);
  if (!report?.snapshot) notFound();
  const r = report.snapshot, regime = r.market_regime as Row, ihsg = r.ihsg as Row, funnel = r.funnel as Row, universe = r.universe as Row;
  const candles = Array.isArray(ihsg?.candles) ? ihsg.candles as Row[] : [], agents = Array.isArray(r.agent_evaluations) ? r.agent_evaluations as Row[] : [], setups = Array.isArray(r.setups) ? r.setups as Row[] : [];
  return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6 print:max-w-none print:bg-white print:text-black"><div className="mb-5 flex items-center justify-between print:hidden"><Link href="/saham/reports" className="font-mono text-xs text-accent hover:underline">← Arsip report</Link><PrintButton /></div>
    <header className="mb-6 flex flex-col gap-4 rounded-2xl border border-border bg-surface p-6 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-wide text-emerald-400">Pulse daily evaluation · stored snapshot</p><h1 className="mt-2 text-3xl font-semibold">Daily Report · {s(r.evaluation_date)}</h1><p className="mt-2 text-sm text-ink-muted">Universe seluruh IDX · {s(universe.symbols_ok)}/{s(universe.eligible_count)} saham berhasil · kualitas data {s((r.data_quality as Row)?.score_pct)}%</p></div><div className="md:text-right"><p className="text-xl font-semibold">{s(regime.label).replaceAll('_', ' ')}</p><p className="font-mono text-xs text-ink-muted">Confidence {s(regime.confidence)}% · cap {s(regime.new_position_cap)} posisi baru</p></div></header>
    <section className="mb-6 grid gap-6 lg:grid-cols-[1.45fr_.55fr]"><article className="rounded-xl border border-border bg-surface p-5"><div className="flex justify-between"><div><p className="font-mono text-[10px] uppercase text-accent">IHSG daily</p><h2 className="text-xl font-semibold">{ihsg.status === 'AVAILABLE' ? `${idr.format(n(ihsg.close))} · ${n(ihsg.change_pct) >= 0 ? '+' : ''}${num.format(n(ihsg.change_pct))}%` : 'DATA NOT AVAILABLE'}</h2></div><span className="font-mono text-xs text-ink-muted">{s(ihsg.trend)}</span></div><MarketChart candles={candles} /><p className="mt-3 text-sm leading-6 text-ink-muted">{s(ihsg.explanation)}</p></article><aside className="rounded-xl border border-border bg-surface p-5"><p className="font-mono text-[10px] uppercase text-emerald-400">Market breadth</p><div className="mt-4 space-y-4">{[['Saham positif', `${num.format(n(regime.breadth_positive_pct))}%`], ['Di atas EMA20', `${num.format(n(regime.above_ema20_pct))}%`], ['Sample', s(regime.sample_size)], ['Return IHSG 5D', `${num.format(n(ihsg.return_5d_pct))}%`], ['Return IHSG 20D', `${num.format(n(ihsg.return_20d_pct))}%`], ['RSI14', num.format(n(ihsg.rsi14))]].map(([label, value]) => <div key={label} className="flex justify-between border-b border-border pb-2 text-sm"><span className="text-ink-muted">{label}</span><b>{value}</b></div>)}</div></aside></section>
    <section className="mb-6 rounded-xl border border-border bg-surface p-5"><p className="font-mono text-[10px] uppercase text-emerald-400">Evaluation funnel</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Technical match', funnel.technical_matches], ['Hard reject', funnel.hard_rejects], ['Shortlisted', funnel.shortlisted], ['Actionable', funnel.actionable], ['Silent accumulation', funnel.silent_accumulation]].map(([label, value]) => <div key={label as string} className="rounded-lg border border-border bg-bg p-4"><p className="font-mono text-2xl font-semibold">{s(value)}</p><p className="font-mono text-[10px] uppercase text-ink-faint">{label as string}</p></div>)}</div></section>
    <section className="mb-6 rounded-xl border border-border bg-surface p-5"><p className="font-mono text-[10px] uppercase text-emerald-400">Agent recap</p><div className="mt-4 grid gap-3 md:grid-cols-2">{agents.map((agent) => <Link key={s(agent.agent_id)} href={`/saham/agents/${s(agent.agent_id)}`} className="rounded-lg border border-border bg-bg p-4 hover:border-emerald-500/50"><div className="flex justify-between"><b>{s(agent.agent_name)}</b><span className="font-mono text-xs text-ink-muted">{s(agent.actionable)} actionable</span></div><p className="mt-2 text-sm text-ink-muted">Pilihan: <span className="text-accent">{s(agent.best_symbol)}</span> · {s(agent.best_action)} · confidence {s(agent.best_confidence)}</p><p className="mt-1 text-xs text-ink-faint">{s(agent.best_rationale)}</p></Link>)}</div></section>
    <section className="rounded-xl border border-border bg-surface p-5"><p className="font-mono text-[10px] uppercase text-emerald-400">Daily recommendations</p><h2 className="mt-1 text-xl font-semibold">Setup prioritas hari ini</h2><div className="mt-4 space-y-3">{setups.map((setup) => <Link key={`${s(setup.rank)}-${s(setup.symbol)}`} href={`/saham/stocks/${s(setup.symbol)}`} className="grid gap-3 rounded-lg border border-border bg-bg p-4 hover:border-emerald-500/50 md:grid-cols-[40px_1fr_repeat(4,auto)] md:items-center"><b className="font-mono text-xl text-ink-faint">#{s(setup.rank)}</b><div><p className="font-semibold text-accent">{s(setup.symbol)} · {s(setup.owner_agent_name)}</p><p className="mt-1 text-xs text-ink-muted">{s(setup.rationale)}</p></div><div><small className="text-ink-faint">Entry</small><p className="font-mono text-xs">{idr.format(n(setup.entry_low))}</p></div><div><small className="text-ink-faint">Stop</small><p className="font-mono text-xs text-negative">{idr.format(n(setup.stop_price))}</p></div><div><small className="text-ink-faint">Target</small><p className="font-mono text-xs text-positive">{idr.format(n(setup.target_price))}</p></div><div><small className="text-ink-faint">R/R</small><p className="font-mono text-xs">{num.format(n(setup.risk_reward))}</p></div></Link>)}</div></section>
  </main>;
}
