let agents=[];
let stocks=[];
let positions=[];
let activities=[];
let overviewSnapshot=null;
let readinessSnapshot=null;
let reportSnapshot=null;
const STOCK_PAGE_VERSION='20260827d';
const stockHref=symbol=>`/stocks/${encodeURIComponent(symbol)}?app=${STOCK_PAGE_VERSION}`;

const $=selector=>document.querySelector(selector);
const agentGrid=$('#agentGrid');
const screenerRows=$('#screenerRows');
const positionRows=$('#positionRows');
const activityFeed=$('#activityFeed');
const dailyTopSetups=$('#dailyTopSetups');
const agentDispatch=$('#agentDispatch');

function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function number(value){return Number(value||0).toLocaleString('id-ID')}
function percentValue(value){return value==null?'N/A':`${Number(value).toLocaleString('id-ID',{minimumFractionDigits:0,maximumFractionDigits:2})}%`}
function idrCompact(value){return `Rp ${(Number(value||0)/1e6).toLocaleString('id-ID',{maximumFractionDigits:2})} jt`}
function signed(value){const n=Number(value||0);return `${n>=0?'+':'−'}${Math.abs(n).toLocaleString('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2})}%`}
function dateTime(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?String(value):d.toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'})+' WIB'}
function agentType(value){return String(value||'all').replaceAll('_','-')}
function signalClass(value){return ['BUY','ACCUMULATE','ACTIONABLE','FILLED'].includes(String(value).toUpperCase())?'buy':'watch'}
function decisionLabel(action,status){const normalized=String(status||'').toUpperCase();if(normalized==='REJECTED_BY_RISK')return `${action} · RISK REJECT`;if(normalized==='REJECTED_PORTFOLIO_CAP')return `${action} · CAP REJECT`;if(normalized==='REJECTED_DELAYED_DATA')return `${action} · DATA REJECT`;return action||status||'NOT EVALUATED'}
async function fetchJson(url){const response=await fetch(url,{cache:'no-store',credentials:'same-origin'});if(!response.ok)throw new Error(`${url} · HTTP ${response.status}`);return response.json()}

function renderAgents(){
  agentGrid.innerHTML=agents.map(a=>`<article class="agent-card" data-agent="${esc(a.id)}" role="link" tabindex="0"><div class="agent-head"><span class="agent-icon">${esc(a.icon)}</span><span class="agent-state ${a.state==='active'?'':'waiting'}">● ${esc(a.state)}</span></div><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><div class="agent-equity">${esc(a.equity)}</div><div class="agent-pnl ${a.pnl.startsWith('+')?'positive':'negative'}">${esc(a.pnl)} all time</div><div class="agent-stats"><span>POSITIONS<b>${a.positions}</b></span><span>WIN RATE · ${esc(a.winSource)}<b>${esc(a.win)}</b></span><span>OPEN RISK<b>${esc(a.risk)}</b></span></div></article>`).join('')||'<p class="empty-note">Belum ada ledger agen.</p>';
  agentGrid.querySelectorAll('[data-agent]').forEach(card=>{card.addEventListener('click',()=>location.href=`/agents/${card.dataset.agent}`);card.addEventListener('keydown',e=>{if(e.key==='Enter')card.click()})});
  const active=agents.filter(a=>a.state==='active').length, research=agents.length-active;
  $('#agentLegend').innerHTML=`<span><i class="legend-dot active-dot"></i>${active} active</span><span><i class="legend-dot waiting-dot"></i>${research} research/scanning</span>`;
}

function stockMatchesFilter(stock,filter){return filter==='all'||(filter==='intraday'?stock.isIntraday:stock.type===filter)}
function updateFilterCounts(){document.querySelectorAll('.filter-button').forEach(button=>{button.querySelector('b').textContent=button.dataset.filter==='all'?stocks.length:stocks.filter(stock=>stockMatchesFilter(stock,button.dataset.filter)).length})}

function renderStocks(filter='all',query=''){
  const q=query.trim().toLowerCase();
  const filtered=stocks.filter(s=>stockMatchesFilter(s,filter)&&(!q||s.symbol.toLowerCase().includes(q)||s.name.toLowerCase().includes(q)));
  screenerRows.innerHTML=filtered.map(s=>`<tr data-symbol="${esc(s.symbol)}" tabindex="0"><td><div class="symbol-cell"><span class="mini-logo">${esc(s.symbol.slice(0,2))}</span><span><strong>${esc(s.symbol)}</strong><small>${esc(s.name)}${s.isIntraday?` · INTRA #${s.intradayRank}`:''}</small></span></div></td><td><strong>${esc(s.price)}</strong><br><small class="${s.changeValue>=0?'positive':'negative'}">${esc(s.change)}</small></td><td><span class="signal-badge ${signalClass(s.signal)}">${esc(s.signal||'NOT EVALUATED')}</span></td><td><span class="score"><b>${s.score??'—'}</b><i style="--score:${Math.max(0,Math.min(100,Number(s.score||0)))}%"></i></span></td><td>${esc(s.flow)}</td><td><span class="agent-chip">${esc(s.agent)}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty-note">Tidak ada emiten yang cocok dengan filter ini.</td></tr>';
  screenerRows.querySelectorAll('tr[data-symbol]').forEach(row=>{row.addEventListener('click',()=>location.href=stockHref(row.dataset.symbol));row.addEventListener('keydown',e=>{if(e.key==='Enter')row.click()})});
}

function renderPositions(){
  positionRows.innerHTML=positions.map(p=>`<tr data-symbol="${esc(p.symbol)}" tabindex="0"><td><div class="symbol-cell"><span class="mini-logo">${esc(p.symbol.slice(0,2))}</span><strong>${esc(p.symbol)}</strong></div></td><td><span class="agent-chip">${esc(p.agent)}</span></td><td>${esc(p.entry)}</td><td>${esc(p.last)}</td><td>${p.lots}</td><td class="${p.pnlValue>=0?'positive':'negative'}">${esc(p.pnl)}</td><td><div class="progress-pair">${esc(p.plan)}<div><span style="width:${Math.max(5,Math.min(100,p.progress))}%"></span></div></div></td><td><span class="status-pill live">● ${esc(p.status)}</span></td></tr>`).join('')||'<tr><td colspan="8" class="empty-note">Belum ada posisi paper yang terbuka.</td></tr>';
  positionRows.querySelectorAll('tr[data-symbol]').forEach(row=>{row.addEventListener('click',()=>location.href=stockHref(row.dataset.symbol));row.addEventListener('keydown',e=>{if(e.key==='Enter')row.click()})});
}

function activityDetails(value){if(typeof value==='string')return value;if(!value||typeof value!=='object')return 'Snapshot tersimpan';return Object.entries(value).slice(0,3).map(([key,val])=>`${key.replaceAll('_',' ')}: ${val}`).join(' · ')||'Snapshot tersimpan'}
function renderActivity(){
  activityFeed.innerHTML=activities.map(a=>{const symbol=a.symbol||'SYS',title=a.agent_name||a.agent_id||'Engine';return `<div class="activity-row ${a.symbol?'is-link':''}" ${a.symbol?`data-symbol="${esc(a.symbol)}" role="link" tabindex="0"`:''}><time>${esc(dateTime(a.created_at))}</time><span class="activity-symbol">${esc(symbol.slice(0,2))}</span><p><strong>${esc(title)}</strong> ${esc(String(a.event||'event').replaceAll('_',' ').toLowerCase())} <span>· ${esc(activityDetails(a.details))}</span></p><span>${esc(a.kind||'AUDIT')}</span></div>`}).join('')||'<p class="empty-note">Belum ada decision log tersimpan.</p>';
  activityFeed.querySelectorAll('[data-symbol]').forEach(row=>{row.addEventListener('click',()=>location.href=stockHref(row.dataset.symbol));row.addEventListener('keydown',e=>{if(e.key==='Enter')row.click()})});
}

function renderSidePanels(){
  dailyTopSetups.innerHTML=stocks.slice(0,6).map((s,i)=>`<div class="daily-setup" data-symbol="${esc(s.symbol)}" role="link" tabindex="0"><span class="rank">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(s.symbol)}</strong><small>${esc(s.agent)} · ${esc(s.signal)}</small></span><b>${s.score??'—'}</b><em class="${s.changeValue>=0?'positive':'negative'}">${esc(s.change)}</em></div>`).join('')||'<p class="empty-note">Belum ada setup tersimpan.</p>';
  dailyTopSetups.querySelectorAll('[data-symbol]').forEach(row=>{row.addEventListener('click',()=>location.href=stockHref(row.dataset.symbol));row.addEventListener('keydown',e=>{if(e.key==='Enter')row.click()})});
  agentDispatch.innerHTML=agents.map(a=>`<div><span>${esc(a.icon)}</span><p><strong>${esc(a.name)}</strong><small>${a.positions} posisi · risk ${esc(a.risk)}</small></p><b class="${a.pnl.startsWith('+')?'positive':'negative'}">${esc(a.pnl)}</b></div>`).join('')||'<p class="empty-note">Belum ada data agen.</p>';
}

const readinessLabels={idx_universe_below_minimum:'Universe IDX belum lengkap',idx_holiday_calendar_not_validated:'Kalender libur IDX belum tervalidasi',latest_report_is_stale:'Laporan evaluasi sudah stale',no_successful_engine_run:'Belum ada engine run sukses',no_successful_eod_run:'Belum ada scan harian sukses',latest_eod_universe_incomplete:'Scan harian belum mencakup universe IDX terbaru',no_cached_market_candles:'Belum ada candle tersimpan',demo_mode_enabled_in_production:'Demo mode masih aktif',production_access_control_not_configured:'Akses production belum diproteksi',market_data_terms_not_acknowledged:'Ketentuan data belum dikonfirmasi',yahoo_provider_disabled:'Provider Yahoo nonaktif',paper_only_guard_disabled:'Guard paper-only nonaktif',arjum_api_key_not_configured:'Arjum API belum dikonfigurasi',yahoo_idx_data_delayed_paper_only:'Yahoo IDX delayed · paper-only'};
function renderReadiness(status){
  readinessSnapshot=status;const banner=$('#readinessBanner'),issues=[...(status.blockers||[]),...(status.warnings||[])],ready=status.ready;
  banner.className=`readiness-banner ${ready?'ready':'blocked'}`;banner.querySelector('.readiness-icon').textContent=ready?'✓':'!';banner.querySelector('strong').textContent=ready?'System siap untuk paper production':'Belum siap production';banner.querySelector('p').textContent=ready?'Semua readiness gate lolos. Eksekusi tetap paper-only.':`${status.blockers?.length||0} blocker · ${status.warnings?.length||0} warning · ${issues.slice(0,2).map(x=>readinessLabels[x]||x).join(' · ')}`;$('#readinessCount').textContent=status.blockers?.length||0;$('#readinessDetails').textContent=ready?'System status':'Review blockers';$('#pipelineMode').textContent=`${status.environment} · ${status.paper_only?'paper only':'unsafe mode'} · ${status.demo_mode?'demo seed':'stored engine data'}`;
}

function renderLatestDecision(decision){
  const card=$('#latestDecision');if(!decision){card.removeAttribute('data-symbol');$('#latestDecisionTicker').textContent='Belum ada keputusan';$('#openPlan').disabled=true;return}
  card.dataset.symbol=decision.symbol;$('#latestDecisionLogo').textContent=decision.symbol.slice(0,2);$('#latestDecisionTicker').innerHTML=`${esc(decision.symbol)} <span>${esc(decision.status||'STORED')}</span>`;$('#latestDecisionMeta').textContent=`${decision.agent_name} · ${dateTime(decision.evaluated_at)}`;$('#latestDecisionSignal').textContent=decision.action;$('#latestDecisionSignal').className=`signal-badge ${signalClass(decision.action)}`;
  const confidence=Number(decision.confidence||0);$('#latestDecisionConfidence').textContent=`${confidence||'—'} / 100`;$('#latestDecisionConfidenceBar').style.width=`${Math.max(0,Math.min(100,confidence))}%`;$('#latestDecisionReason').innerHTML=`<div><span>01</span><p><strong>Stored rationale</strong>${esc(decision.rationale||'Belum ada rationale tersimpan.')}</p></div>`;
  $('#latestEntry').textContent=decision.entry_low?`${number(decision.entry_low)}–${number(decision.entry_high||decision.entry_low)}`:'—';$('#latestStop').textContent=decision.stop_price?number(decision.stop_price):'—';$('#latestTarget').textContent=decision.target_price?number(decision.target_price):'—';$('#latestRR').textContent=decision.risk_reward?`1 : ${number(decision.risk_reward)}`:'—';$('#latestDecisionStatus').textContent='Stored snapshot';
  $('#modalPlanRef').textContent=`TRADING PLAN · ${decision.symbol}`;$('#modalPlanTitle').textContent=`${decision.symbol} · ${decision.action}`;$('#modalAgent').textContent=decision.agent_name;$('#modalRisk').textContent=decision.equity_risk_pct?`${number(decision.equity_risk_pct)}%`:'—';$('#modalEntry').textContent=$('#latestEntry').textContent;$('#modalStatus').textContent=decision.status||'—';$('#modalRationale').textContent=decision.rationale||'Belum ada rationale tersimpan.';$('#openPlan').disabled=false;
}

function renderReport(report){
  reportSnapshot=report;const funnel=report.funnel||{},universe=report.universe||{},quality=report.data_quality||{},regime=report.market_regime||{};
  $('#reportSnapshot').textContent=dateTime(report.generated_at);$('#reportUniverse').textContent=`${number(universe.symbols_ok??universe.evaluated_count)} / ${number(universe.eligible_count)} data tersedia`;$('#reportSource').textContent=`${report.schema_version?`Snapshot v${report.schema_version}`:'Stored evaluation'} · no rescan`;$('#reportQuality').textContent=quality.score_pct==null?'DATA NOT AVAILABLE':`${number(quality.score_pct)}% · ${quality.errors?.length?'Perlu review':'Valid'}`;$('#reportQuality').className=quality.errors?.length?'negative':'positive';
  const actionable=funnel.actionable??0,shortlisted=funnel.shortlisted??report.setups?.length??0,ihsg=report.ihsg||{},breadth=Number(regime.breadth_positive_pct),above=Number(regime.above_ema20_pct);let stance='WAIT / SELECTIVE',meaning='Arah pasar belum konsisten; hanya ambil setup dengan trading plan lengkap.';if(ihsg.trend==='BULLISH'&&breadth<55){stance='SELECTIVE BUY';meaning='IHSG masih dalam struktur naik, tetapi penguatan belum merata. Seleksi saham lebih penting daripada mengikuti indeks.'}else if(ihsg.trend==='BULLISH'&&breadth>=55){stance='RISK-ON TERKONTROL';meaning='Arah IHSG dan breadth sejalan, namun setiap entry tetap harus lolos stop dan risk/reward.'}else if(ihsg.trend==='BEARISH'){stance='DEFENSIVE';meaning='Struktur IHSG melemah; kurangi agresivitas dan utamakan perlindungan modal.'}$('#reportHeadline').textContent=`${stance} · ${actionable} trading plan siap ditindak.`;$('#reportBrief').textContent=meaning;
  $('#reportInsights').innerHTML=[`${number(funnel.universe_scanned??universe.symbols_ok)} saham dipindai, ${number(funnel.unique_candidates??universe.evaluated_count)} kandidat unik masuk evaluasi agen.`,`${shortlisted} sinyal Buy/Accumulate adalah jumlah keputusan agen, bukan jumlah ticker unik; ${actionable} plan lolos seluruh risk gate.`,above-breadth>=10?`Breadth ${number(breadth)}% tertinggal dari saham di atas EMA20 ${number(above)}%: momentum sangat pendek lebih lemah daripada tren menengah.`:'Breadth dan struktur EMA20 relatif searah.'].map(text=>`<li>${esc(text)}</li>`).join('');
  $('#reportRegime').textContent=String(regime.label||'DATA NOT AVAILABLE').replaceAll('_',' ');$('#reportRegimeConfidence').textContent=regime.confidence==null?'Confidence tidak tersedia':`Confidence ${regime.confidence}% · breadth ${regime.breadth_positive_pct??'—'}% · above EMA20 ${regime.above_ema20_pct??'—'}%`;$('#reportFooterSource').textContent=`${report.report_id||'Stored evaluation'} · generated ${dateTime(report.generated_at)} · no rescan`;
  const grouped=new Map();(report.setups||[]).forEach(s=>{const rows=grouped.get(s.symbol)||[];rows.push(s);grouped.set(s.symbol,rows)});const setups=[...grouped.values()].map(rows=>({primary:[...rows].sort((a,b)=>Number(b.score||0)-Number(a.score||0))[0],agents:[...new Set(rows.map(x=>x.owner_agent_name||x.owner_agent))]})).sort((a,b)=>Number(b.primary.score||0)-Number(a.primary.score||0));dailyTopSetups.innerHTML=setups.slice(0,6).map(({primary:s,agents},i)=>`<div class="daily-setup" data-symbol="${esc(s.symbol)}" role="link" tabindex="0"><span class="rank">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(s.symbol)}</strong><small>${esc(agents.join(', '))} · ${esc(decisionLabel(s.action,s.status))}</small></span><b>${s.score??'—'}</b><em class="${Number(s.change_pct||0)>=0?'positive':'negative'}">${s.change_pct==null?'—':signed(s.change_pct)}</em></div>`).join('')||'<p class="empty-note">Belum ada sinyal Buy/Accumulate pada snapshot ini.</p>';
  dailyTopSetups.querySelectorAll('[data-symbol]').forEach(row=>{row.addEventListener('click',()=>location.href=stockHref(row.dataset.symbol));row.addEventListener('keydown',e=>{if(e.key==='Enter')row.click()})});
  const evaluations=report.agent_evaluations||[];if(evaluations.length)agentDispatch.innerHTML=evaluations.map(a=>`<div><span>${esc((a.agent_name||a.agent_id).slice(0,2).toUpperCase())}</span><p><strong>${esc(a.agent_name||a.agent_id)}</strong><small>${a.evaluated} evaluasi · ${a.actionable} actionable · ${(a.waiting||0)+(a.research||0)} wait/research · ${a.rejected} rejected</small></p><b>${a.best_confidence==null?'—':`${a.best_confidence} · ${esc(a.best_symbol)}`}</b></div>`).join('');
}

function renderWatchItems(status,usage){
  const items=[];(status.blockers||[]).slice(0,2).forEach(item=>items.push(['Production blocker',readinessLabels[item]||item]));(status.warnings||[]).slice(0,2).forEach(item=>items.push(['Data warning',readinessLabels[item]||item]));const left=Math.max(0,Number(usage.request_limit||1000)-Number(usage.requests_used||0));items.push(['Arjum quota',`${number(left)} request tersisa; dashboard tidak melakukan refresh otomatis.`]);$('#reportWatchItems').innerHTML=items.map(([title,body])=>`<li><b>${esc(title)}</b><span>${esc(body)}</span></li>`).join('');
}

function renderEquityCurve(points){if(!points?.length)return;const values=points.map(point=>Number(point.equity)),min=Math.min(...values),max=Math.max(...values),span=max-min||1,d=values.map((value,index)=>`${index?'L':'M'} ${2+(236*index/Math.max(1,values.length-1))} ${52-46*(value-min)/span}`).join(' ');document.querySelectorAll('.sparkline path').forEach((path,index)=>path.setAttribute('d',index?`${d} L238 58 L2 58Z`:d))}
async function loadReport(date='latest'){try{renderReport(await fetchJson(`/api/reports/${date}`))}catch(error){$('#reportHeadline').textContent='Laporan belum tersedia';$('#reportBrief').textContent=error.message}}

async function bootstrap(){
  try{
    // The screener has the full IDX universe. Do not hold the whole dashboard
    // hostage while that larger payload is being prepared.
    const screenerRequest=fetchJson('/api/screener');
    const [overview,livePositions,health,engineStatus,systemStatus,activity,reports,report]=await Promise.all([fetchJson('/api/overview'),fetchJson('/api/positions'),fetchJson('/api/health'),fetchJson('/api/engine/status'),fetchJson('/api/system/status'),fetchJson('/api/activity?limit=16'),fetchJson('/api/reports'),fetchJson('/api/reports/latest')]);overviewSnapshot=overview;
    agents=(overview.agents||[]).map(a=>({id:a.id,icon:a.id.split('-').map(x=>x[0]).join('').toUpperCase().slice(0,2),name:a.name,desc:a.description,equity:idrCompact(a.equity),pnl:signed(a.pnl_pct),positions:livePositions.filter(p=>p.agent_id===a.id&&p.status==='OPEN').length,win:percentValue(a.display_win_rate),winSource:(a.win_rate_source||'N/A').toUpperCase(),risk:percentValue(a.open_risk_pct),state:a.status==='ACTIVE'?'active':'research'}));
    stocks=[];
    positions=livePositions.filter(p=>p.status==='OPEN').map(p=>{const entry=Number(p.entry_price),last=Number(p.last_price),stop=Number(p.stop_price||entry),target=Number(p.target_price||entry),progress=target===entry?0:(last-entry)/(target-entry)*100;return {symbol:p.symbol,agent:p.agent_name,entry:number(entry),last:number(last),lots:p.lots,pnl:signed(p.pnl_pct),pnlValue:Number(p.pnl_pct||0),plan:`${number(stop)} / ${number(target)}`,progress,status:p.strategy_version==='2.0'?p.status:'LEGACY'}});activities=activity.rows||[];
    const starting=(overview.agents||[]).reduce((sum,a)=>sum+Number(a.starting_equity||0),0),total=Number(overview.total_equity||0),totalPnl=starting?(total-starting)/starting*100:0;$('#totalFundEquity').textContent=idrCompact(total);$('#totalFundPnl').textContent=`${signed(totalPnl)} · ${idrCompact(total-starting)} all time`;$('#openPositionCount').textContent=positions.length;$('#todayPnl').textContent=overview.today_pnl===null?'—':idrCompact(overview.today_pnl);$('#todayPnlFoot').textContent=overview.today_pnl===null?'Snapshot pembanding belum tersedia':`${overview.today_pnl>=0?'▲':'▼'} versus snapshot equity sebelumnya`;$('#positionMarketValue').textContent=`Market value ${idrCompact(overview.position_stats?.market_value)} · UPL ${idrCompact(overview.position_stats?.unrealized)}`;$('#positionsMarketValue').textContent=idrCompact(overview.position_stats?.market_value);$('#positionsUnrealized').textContent=idrCompact(overview.position_stats?.unrealized);$('#positionsUnrealized').className=Number(overview.position_stats?.unrealized)>=0?'positive':'negative';
    const risk=Number(overview.open_risk_pct||0),usage=overview.provider_usage||{},usageDate=usage.usage_date?new Date(`${usage.usage_date}T12:00:00+07:00`).toLocaleDateString('id-ID',{day:'2-digit',month:'short'}):'hari ini';$('#systemRisk').textContent=`${number(risk)}%`;document.querySelector('.risk-track span').style.width=`${Math.min(100,risk/12*100)}%`;$('#arjumUsage').textContent=`${number(usage.requests_used)} / ${number(usage.request_limit||1000)} · ${usageDate}`;document.querySelector('.quota-track span').style.width=`${Math.min(100,Number(usage.requests_used||0)/Number(usage.request_limit||1000)*100)}%`;
    const run=engineStatus.latest_run;$('#yahooFreshness').textContent=run?`${run.status} · ${run.symbols_ok}/${run.universe_size} symbols`:'No run';$('#marketPhase').textContent=String(engineStatus.market_phase||'UNKNOWN').replaceAll('_',' ');$('#engineRunStatus').textContent=run?`${run.timeframe} · ${dateTime(run.completed_at)}`:'Engine belum berjalan';const hour=Number(new Date().toLocaleString('en-US',{hour:'numeric',hour12:false,timeZone:'Asia/Jakarta'})),greeting=hour<11?'Selamat pagi':hour<15?'Selamat siang':'Selamat sore';$('#heroGreeting').innerHTML=`${greeting}. <span>Fund ${totalPnl>=0?'positif':'perlu perhatian'}.</span>`;
    renderReadiness(systemStatus);renderLatestDecision(overview.latest_decision);renderEquityCurve(overview.equity_curve);renderAgents();updateFilterCounts();renderStocks();renderPositions();renderActivity();renderSidePanels();renderReport(report);renderWatchItems(systemStatus,overview.provider_usage||{});
    screenerRequest.then(screen=>{stocks=(screen.rows||[]).map(s=>({symbol:s.symbol,name:s.name,price:number(s.last_price),change:signed(s.change_pct),changeValue:Number(s.change_pct||0),signal:decisionLabel(s.signal,s.decision_status||s.evaluation_status),score:s.evaluation_score,flow:s.flow_verdict||'DATA NOT AVAILABLE',agent:s.owner_agent_name||'Belum dievaluasi',type:agentType(s.owner_agent_id),isIntraday:Boolean(s.is_intraday),intradayRank:s.intraday_rank}));updateFilterCounts();renderStocks($('.filter-button.active').dataset.filter,$('#globalSearch').value);renderSidePanels()}).catch(()=>{screenerRows.innerHTML='<tr><td colspan="6" class="empty-note">Screener belum tersedia. Coba muat ulang.</td></tr>'});
    const options=reports.rows||[];$('#reportDate').innerHTML=options.map(row=>`<option value="${esc(row.report_date)}">${new Date(`${row.report_date}T12:00:00+07:00`).toLocaleDateString('id-ID',{dateStyle:'long'})}</option>`).join('')||'<option>Belum ada laporan</option>';$('#reportDate').disabled=!options.length;if(health.environment==='production'&&systemStatus.demo_mode)showToast('Production blocker: demo mode masih aktif');
  }catch(error){$('#heroGreeting').innerHTML='Dashboard <span>belum terhubung.</span>';$('#readinessBanner').className='readiness-banner blocked';$('#readinessBanner').querySelector('strong').textContent='API tidak tersedia';$('#readinessBanner').querySelector('p').textContent=error.message;showToast(`API tidak tersedia: ${error.message}`);renderAgents();renderStocks();renderPositions();renderActivity();renderSidePanels()}
}

bootstrap();
document.querySelectorAll('.filter-button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderStocks(button.dataset.filter,$('#globalSearch').value)}));
$('#globalSearch').addEventListener('input',event=>{renderStocks($('.filter-button.active').dataset.filter,event.target.value);$('#screener').scrollIntoView({behavior:'smooth',block:'center'})});document.addEventListener('keydown',event=>{if(event.key==='/'&&document.activeElement.tagName!=='INPUT'){event.preventDefault();$('#globalSearch').focus()}});$('#mobileMenu').addEventListener('click',()=>$('.sidebar').classList.toggle('open'));document.querySelectorAll('.nav-link').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(item=>item.classList.remove('active'));link.classList.add('active');$('.sidebar').classList.remove('open')}));

const dialog=$('#planDialog');$('#openPlan').addEventListener('click',()=>{if(overviewSnapshot?.latest_decision)dialog.showModal()});$('#latestDecision').addEventListener('click',()=>{if($('#latestDecision').dataset.symbol)location.href=stockHref($('#latestDecision').dataset.symbol)});$('#latestDecision').addEventListener('keydown',event=>{if(event.key==='Enter')$('#latestDecision').click()});$('#closePlan').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
const toast=$('#toast');function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
$('#runAgents').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{const status=await fetchJson('/api/engine/status'),run=status.latest_run;showToast(run?`Engine ${run.status} · ${run.symbols_ok}/${run.universe_size} simbol · ${run.proposals} proposal`:'Engine belum pernah berjalan')}catch(error){showToast(error.message)}finally{event.currentTarget.disabled=false}});$('#readinessShortcut').addEventListener('click',()=>$('#readinessBanner').scrollIntoView({behavior:'smooth',block:'center'}));$('#readinessDetails').addEventListener('click',()=>showToast(readinessSnapshot?.ready?'Semua readiness gate lolos':(readinessSnapshot?.blockers||[]).map(x=>readinessLabels[x]||x).join(' · ')||'Status belum tersedia'));

function answerSnapshot(question){if(!overviewSnapshot)return 'Snapshot belum tersedia.';const lower=question.toLowerCase();if(lower.includes('banding')){const ordered=[...agents].sort((a,b)=>parseFloat(b.pnl.replace(',','.'))-parseFloat(a.pnl.replace(',','.')));return `${ordered[0]?.name||'—'} memimpin return tersimpan (${ordered[0]?.pnl||'—'}). Setiap agen tetap memakai ledger dan risk budget terpisah.`}if(lower.includes('risiko'))return `Open risk gabungan ${number(overviewSnapshot.open_risk_pct)}% dari equity fund. Ini agregasi lintas agen; detail stop dan ukuran lot tersedia pada halaman saham.`;if(lower.includes('scalping')){const agent=agents.find(a=>a.id==='scalping');return `Scalping Desk mencatat return ${agent?.pnl||'—'} dan win rate ${agent?.win||'—'} pada snapshot. Audit net expectancy tetap perlu memasukkan fee dan slippage.`}return `Snapshot memuat ${agents.length} agen, ${stocks.length} emiten hasil evaluasi tersimpan, dan ${positions.length} posisi paper terbuka. Model AI eksternal belum diaktifkan.`}
const consoleForm=$('#consoleForm'),consoleInput=$('#consoleInput'),consoleTranscript=$('#consoleTranscript');function askConsole(question){if(!question.trim())return;consoleTranscript.querySelector('.quick-prompts')?.remove();consoleTranscript.insertAdjacentHTML('beforeend',`<div class="console-message user"><span>YOU</span><p>${esc(question)}</p></div><div class="console-message system"><span>NQ</span><p>${esc(answerSnapshot(question))}</p></div>`);consoleTranscript.scrollTop=consoleTranscript.scrollHeight;consoleInput.value=''}consoleForm.addEventListener('submit',event=>{event.preventDefault();askConsole(consoleInput.value)});document.querySelectorAll('.quick-prompts button').forEach(button=>button.addEventListener('click',()=>askConsole(button.textContent)));
$('#copyReport').addEventListener('click',async()=>{if(!reportSnapshot)return showToast('Belum ada laporan tersimpan');const f=reportSnapshot.funnel||{},r=reportSnapshot.market_regime||{},summary=`Pulse Daily Evaluation — ${reportSnapshot.evaluation_date}\nUniverse: seluruh saham IDX aktif\nRegime: ${r.label||'N/A'} (${r.confidence??'N/A'}%)\nShortlist: ${f.shortlisted??'N/A'} · Actionable: ${f.actionable??'N/A'}\nSource: ${reportSnapshot.source_mode||'stored evaluation'} · tanpa scan ulang.`;try{await navigator.clipboard.writeText(summary);showToast('Ringkasan daily report disalin')}catch{showToast('Clipboard tidak tersedia')}});$('#exportReport').addEventListener('click',()=>{if(!reportSnapshot)return showToast('Belum ada laporan untuk diekspor');const blob=new Blob([JSON.stringify(reportSnapshot,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`nusaquant-report-${reportSnapshot.evaluation_date||'latest'}.json`;link.click();URL.revokeObjectURL(url)});$('#reportDate').addEventListener('change',event=>loadReport(event.target.value));
$('#downloadReportPdf').addEventListener('click',()=>{if(!reportSnapshot)return showToast('Belum ada laporan tersimpan');const date=reportSnapshot.evaluation_date||'latest',link=document.createElement('a');link.href=`/api/reports/${encodeURIComponent(date)}/pdf`;link.download=`NusaQuant_Daily_Report_${date}.pdf`;document.body.appendChild(link);link.click();link.remove();showToast('PDF report sedang disiapkan')});
