const idr=n=>`Rp ${Math.round(Number(n||0)).toLocaleString('id-ID')}`;
const pct=n=>`${Number(n||0)>=0?'+':''}${Number(n||0).toFixed(2).replace('.',',')}%`;
const decimal=(n,digits=2)=>n==null?'—':Number(n).toLocaleString('id-ID',{minimumFractionDigits:0,maximumFractionDigits:digits});
const resultR=n=>n==null?'—':`${decimal(n,2)}R`;
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const stockHref=symbol=>`/stocks/${encodeURIComponent(symbol)}?app=20260827d`;
async function getJSON(url){const res=await fetch(url,{cache:'no-store',credentials:'same-origin'});if(!res.ok){const body=await res.json().catch(()=>({}));const error=new Error(body.error||'request_failed');error.status=res.status;throw error}return res.json()}
const asArray=value=>Array.isArray(value)?value:[];
function routeId(kind){const parts=location.pathname.split('/').filter(Boolean);return ['agent','stock','report'].includes(kind)?parts[1]:null}

function equityChart(rows){
  if(!rows.length)return '<p class="empty-note">Belum ada histori equity.</p>';
  const values=rows.map(r=>Number(r.equity)), min=Math.min(...values), max=Math.max(...values), span=max-min||1;
  const pts=values.map((v,i)=>`${30+i*(660/(values.length-1||1))},${170-(v-min)/span*125}`).join(' ');
  const area=`30,170 ${pts} 690,170`;
  return `<svg class="equity-chart" viewBox="0 0 720 205" role="img" aria-label="Equity curve ${rows.length} hari"><line x1="30" y1="170" x2="690" y2="170"/><line x1="30" y1="45" x2="690" y2="45"/><polygon points="${area}"/><polyline points="${pts}"/><text x="30" y="194">${rows[0].equity_date}</text><text x="690" y="194" text-anchor="end">${rows.at(-1).equity_date}</text><text x="34" y="38">${idr(max)}</text><text x="34" y="164">${idr(min)}</text></svg>`;
}

async function renderAgent(){
  const root=document.querySelector('#agentPage'); if(!root)return;
  try{
    const a=await getJSON(`/api/agents/${encodeURIComponent(routeId('agent'))}`); document.title=`${a.name} · NusaQuant`;
    const strategy=a.strategy||{};
    const winRate=a.performance.win_rate??a.legacy_performance?.win_rate;
    const winRateSource=a.performance.win_rate!=null?'V2':a.legacy_performance?.win_rate!=null?'LEGACY':'N/A';
    root.innerHTML=`
      <header class="detail-hero"><div><p class="eyebrow">${escapeHtml(a.validation_status)} STRATEGY · V${escapeHtml(a.strategy_version)}</p><h1>${escapeHtml(a.name)}</h1><p>${escapeHtml(a.description)} · ledger dan keputusan independen</p></div><div class="hero-number"><strong>${idr(a.equity)}</strong><small class="${a.pnl_pct>=0?'positive':'negative'}">${pct(a.pnl_pct)} all time</small></div></header>
      <section class="detail-metrics"><div class="detail-metric"><small>NET REALIZED P&amp;L · V2</small><strong class="${a.performance.net_pnl>=0?'positive':'negative'}">${idr(a.performance.net_pnl)}</strong></div><div class="detail-metric"><small>WIN RATE · ${winRateSource}</small><strong>${winRate==null?'N/A':`${decimal(winRate)}%`}</strong></div><div class="detail-metric"><small>PROFIT FACTOR · V2</small><strong>${decimal(a.performance.profit_factor)}</strong></div><div class="detail-metric"><small>AVERAGE R · V2</small><strong>${resultR(a.performance.avg_r)}</strong></div><div class="detail-metric"><small>MAX DRAWDOWN</small><strong class="${a.performance.max_drawdown_pct<0?'negative':''}">${decimal(a.performance.max_drawdown_pct)}%</strong></div></section>
      <article class="detail-panel performance-panel"><div class="panel-title-row"><div><p class="eyebrow">PERFORMANCE</p><h2>Equity curve</h2></div><span>${a.equity_history.length} daily snapshots · mark-to-market</span></div>${equityChart(a.equity_history)}</article>
      <div class="detail-grid"><section><article class="detail-panel"><h2>Latest evaluations</h2>${a.decisions.length?a.decisions.map(d=>`<div class="decision-card"><div class="decision-head"><a href="${stockHref(d.symbol)}">${d.symbol}</a><span>${d.name}</span><span class="signal-badge ${d.action==='BUY'?'buy':'watch'}">${d.action} · ${d.confidence||0}</span></div><p>${escapeHtml(d.rationale)}</p><div class="plan-strip"><span><small>ENTRY</small><b>${d.entry_low?`${idr(d.entry_low)}–${idr(d.entry_high)}`:'—'}</b></span><span><small>STOP</small><b class="negative">${d.stop_price?idr(d.stop_price):'—'}</b></span><span><small>TARGET</small><b class="positive">${d.target_price?idr(d.target_price):'—'}</b></span><span><small>EQUITY RISK</small><b>${d.equity_risk_pct}%</b></span></div></div>`).join(''):'<p class="empty-note">Belum ada evaluasi.</p>'}</article></section>
      <aside><article class="detail-panel"><div class="panel-title-row"><h2>Open positions</h2><span>${a.open_position_count??a.positions.length} active</span></div>${a.positions.length?a.positions.map(p=>`<div class="position-card"><a href="${stockHref(p.symbol)}">${p.symbol} · ${p.lots} lot</a><b class="${p.unrealized_pnl>=0?'positive':'negative'}">${idr(p.unrealized_pnl)}</b><p>Nilai kini ${idr(p.market_value)} · modal ${idr(p.entry_value)}<br>Entry ${idr(p.entry_price)} · last ${idr(p.last_price)} · stop ${idr(p.stop_price)} · ${escapeHtml(p.strategy_version||'legacy')}</p></div>`).join(''):'<p class="empty-note">Agen sedang flat.</p>'}</article><article class="detail-panel"><div class="panel-title-row"><h2>Pending orders</h2><span>${a.pending_orders?.length||0} waiting fill</span></div>${a.pending_orders?.length?a.pending_orders.map(o=>`<div class="position-card"><a href="${stockHref(o.symbol)}">${o.symbol} · ${o.lots} lot</a><b>${idr(o.order_value)}</b><p>Limit ${idr(o.limit_price)} · stop ${idr(o.stop_price)} · target ${idr(o.target_price)}<br>Berlaku sampai ${escapeHtml(o.expires_at||'—')} · ${escapeHtml(o.timeframe||'—')} · v${escapeHtml(o.strategy_version||'—')}</p></div>`).join(''):'<p class="empty-note">Tidak ada order menunggu fill.</p>'}</article><article class="detail-panel"><h2>Hard risk policy</h2><p class="method-note">Target risiko 3%, maksimum 5% per campaign. Eksposur gabungan maksimal 80% equity dan open risk maksimal 10%. Stop wajib mengikuti tick IDX. Reward bersih setelah fee minimal 1:1,5.</p><div class="data-provenance">Read-only snapshot · membuka halaman ini tidak menjalankan scan.</div></article></aside></div>
      <article class="detail-panel strategy-panel"><div class="panel-title-row"><div><p class="eyebrow">PLAYBOOK</p><h2>Penjelasan strategi</h2></div><span>${escapeHtml(strategy.timeframes||'—')}</span></div><p class="strategy-objective">${escapeHtml(strategy.objective||'Strategi belum didokumentasikan.')}</p><div class="strategy-rules"><div><h3>Entry rules</h3><ol>${(strategy.entry_rules||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></div><div><h3>Exit & management</h3><ol>${(strategy.exit_rules||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></div><div><h3>No-trade conditions</h3><ol>${(strategy.no_trade||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></div></div></article>
      <article class="detail-panel journal-panel"><div class="panel-title-row"><div><p class="eyebrow">AUDITABLE RECORD</p><h2>Trade journal</h2></div><span>${a.performance.closed_trades} trade v2 · ${a.legacy_performance?.closed_trades||0} legacy</span></div><div class="journal-table-wrap"><table class="journal-table"><thead><tr><th>Trade</th><th>Opened / closed</th><th>Lots</th><th>Entry / exit</th><th>Nilai posisi</th><th>Fees</th><th>Net P&amp;L</th><th>Result</th><th>Exit reason</th></tr></thead><tbody>${a.trade_journal.length?a.trade_journal.map(t=>`<tr><td><a href="${stockHref(t.symbol)}">${t.symbol}</a><small>${escapeHtml(t.setup||'—')} · ${escapeHtml(t.strategy_version||'legacy')}</small></td><td>${t.opened_at.slice(0,10)}<small>${t.closed_at?t.closed_at.slice(0,10):'OPEN'}</small></td><td>${t.lots}</td><td>${idr(t.entry_price)}<small>${t.exit_price?idr(t.exit_price):'—'}</small></td><td>${idr(t.entry_value)}<small>${t.exit_value?`Keluar ${idr(t.exit_value)}`:'Masih terbuka'}</small></td><td>${idr(t.fees)}</td><td class="${(t.net_pnl||0)>=0?'positive':'negative'}">${idr(t.net_pnl||0)}</td><td><span class="r-badge ${(t.r_multiple||0)>=0?'positive':'negative'}">${resultR(t.r_multiple)}</span></td><td>${escapeHtml(t.exit_reason||'—')}<small>${escapeHtml(t.notes||'')}</small></td></tr>`).join(''):'<tr><td colspan="9">Belum ada trade journal.</td></tr>'}</tbody></table></div></article>`;
  }catch(e){root.innerHTML=`<div class="error-state">Agent tidak ditemukan: ${escapeHtml(e.message)}</div>`}
}

function unavailable(label='DATA NOT AVAILABLE'){return `<div class="unavailable"><b>${label}</b><span>Tidak ada nilai yang diestimasi.</span></div>`}
function arjumReport(sections){
  const rows=asArray(sections);if(!rows.length)return '';
  return `<details class="arjum-report" open><summary><span>Laporan analisis Arjum</span><small>${rows.length} bagian · data tersimpan</small></summary><div class="arjum-report-body">${rows.map(section=>`<section><h3>${escapeHtml(section.title)}</h3>${asArray(section.lines).map(line=>`<p>${escapeHtml(line)}</p>`).join('')}</section>`).join('')}</div></details>`;
}
function stockChart(chart,timeframe=chart.default_timeframe){
  const rows=chart.series?.[timeframe]||chart.candles||[];
  if(!rows.length)return unavailable();
  const overlays=chart.overlays?.[timeframe]||chart.overlays||{}, values=rows.flatMap(x=>[x.h,x.l]), min=Math.min(...values), max=Math.max(...values), span=max-min||1, w=900;
  const x=i=>42+i*((w-84)/(rows.length-1||1)), y=v=>210-(v-min)/span*165, maxVol=Math.max(1,...rows.map(r=>r.v));
  const candleWidth=Math.max(2,Math.min(8,720/rows.length));
  const candles=rows.map((r,i)=>`<g class="chart-candle ${r.c>=r.o?'up':'down'}" data-index="${i}" tabindex="0"><title>${escapeHtml(r.t)} · O ${r.o} · H ${r.h} · L ${r.l} · C ${r.c} · V ${r.v}</title><line x1="${x(i)}" y1="${y(r.h)}" x2="${x(i)}" y2="${y(r.l)}"/><rect x="${x(i)-candleWidth/2}" y="${Math.min(y(r.o),y(r.c))}" width="${candleWidth}" height="${Math.max(2,Math.abs(y(r.o)-y(r.c)))}"/><rect class="volume" x="${x(i)-candleWidth/2}" y="${252-r.v/maxVol*28}" width="${candleWidth}" height="${r.v/maxVol*28}"/></g>`).join('');
  const level=(v,cls,label)=>v?`<line class="level ${cls}" x1="28" y1="${y(v)}" x2="872" y2="${y(v)}"/><text class="level-label ${cls}" x="868" y="${y(v)-4}" text-anchor="end">${label} ${Number(v).toLocaleString('id-ID')}</text>`:'';
  return `<svg class="stock-chart" viewBox="0 0 900 270" role="img" aria-label="${timeframe} cached OHLCV chart">${candles}${level(overlays.ema20,'ema','EMA20')}${level(overlays.vwap,'vwap','VWAP')}${level(overlays.support?.[0],'support','SUPPORT')}${level(overlays.resistance?.[0],'resistance','RESISTANCE')}<text x="42" y="262">${escapeHtml(rows[0].t)}</text><text x="858" y="262" text-anchor="end">${escapeHtml(rows.at(-1).t)}</text><text x="8" y="50">${Number(max).toLocaleString('id-ID')}</text><text x="8" y="210">${Number(min).toLocaleString('id-ID')}</text></svg>`;
}
function candleDetail(row,timeframe){return `<span><small>${escapeHtml(timeframe)} · ${escapeHtml(row.t)}</small><b class="${row.c>=row.o?'positive':'negative'}">${row.c>=row.o?'▲':'▼'} ${idr(row.c)}</b></span><span><small>OPEN / HIGH</small><b>${idr(row.o)} / ${idr(row.h)}</b></span><span><small>LOW / CLOSE</small><b>${idr(row.l)} / ${idr(row.c)}</b></span><span><small>VOLUME</small><b>${Number(row.v||0).toLocaleString('id-ID')}</b></span>`}
function bindStockChart(root,stock,timeframe){
  const rows=stock.chart.series?.[timeframe]||stock.chart.candles||[], inspector=root.querySelector('#candleInspector');
  const show=index=>{if(rows[index]&&inspector)inspector.innerHTML=candleDetail(rows[index],timeframe)};
  root.querySelectorAll('.chart-candle').forEach(el=>{const index=Number(el.dataset.index);el.addEventListener('pointerenter',()=>show(index));el.addEventListener('focus',()=>show(index));el.addEventListener('click',()=>show(index))});
  if(rows.length)show(rows.length-1);
}
const shown=v=>v===null||v===undefined||v===''?'—':String(v);
function planValue(value, formatter=x=>x){return value===null||value===undefined?'—':formatter(value)}
function renderPlan(view){const p=view.plan||{};return `<details class="agent-plan"><summary><span><a href="/agents/${view.agent_id}">${escapeHtml(view.agent_name)}</a><small>${escapeHtml(view.horizon)}</small></span><b class="action-${String(view.action).toLowerCase()}">${escapeHtml(view.action.replaceAll('_',' '))}</b><em>${view.confidence??'—'}</em><i>${escapeHtml(p.status||'DRAFT')}</i></summary><div class="plan-body"><p>${escapeHtml(view.rationale)}</p><div class="plan-grid"><span><small>ENTRY ZONE</small><b>${p.entry_low?`${idr(p.entry_low)}–${idr(p.entry_high)}`:'—'}</b></span><span><small>ORDER TYPE</small><b>${p.order_type||'—'}</b></span><span><small>STOP / DISTANCE</small><b>${planValue(p.stop_price,idr)} · ${planValue(p.stop_distance_pct,x=>x+'%')}</b></span><span><small>TARGETS</small><b>${p.targets?.length?p.targets.map(idr).join(' · '):'—'}</b></span><span><small>R/R · EQUITY RISK</small><b>${p.risk_reward??'—'} · ${p.equity_risk_pct??'—'}%</b></span><span><small>LOTS · VALID UNTIL</small><b>${p.lots??'—'} · ${p.valid_until?.slice(0,16).replace('T',' ')||'—'}</b></span></div><div class="plan-rules"><div><strong>Confirmation</strong>${(p.confirmation||[]).map(x=>`<span>✓ ${escapeHtml(x)}</span>`).join('')||'<span>—</span>'}</div><div><strong>Cancellation</strong>${(p.cancellation||[]).map(x=>`<span>× ${escapeHtml(x)}</span>`).join('')||'<span>—</span>'}</div><div><strong>Management</strong>${(p.management||[]).map(x=>`<span>→ ${escapeHtml(x)}</span>`).join('')||'<span>—</span>'}</div></div></div></details>`}

async function renderStock(){
  const root=document.querySelector('#stockPage');if(!root)return;
  try{
    const s=await getJSON(`/api/stocks/${encodeURIComponent(routeId('stock'))}`);document.title=`${s.symbol} · NusaQuant`;
    const score=s.scores||{}, tech=s.technical||{}, flow=s.flow||{}, arjum=s.arjum||{}, fund=s.fundamental||{};
    const arjumPayload=arjum.payload||{}, brokerPayload=arjumPayload.broker_summary||{}, accumulationPayload=arjumPayload.broker_accumulation||{}, seasonalPayload=arjumPayload.seasonal||{};
    const fundamentalMetrics=asArray(fund.indicators);
    const fundamentalValue=item=>item.value==null?'DATA NOT AVAILABLE':item.unit==='IDR'?idr(item.value):`${Number(item.value).toLocaleString('id-ID',{maximumFractionDigits:2})}${item.unit==='%'?'%':item.unit==='×'?'×':''}`;
    root.innerHTML=`
      <header class="stock-hero"><div><p class="eyebrow">${escapeHtml(s.sector||'—')} · ${escapeHtml(s.subsector||'—')}</p><h1>${s.symbol} <span>${escapeHtml(s.name)}</span></h1><div class="stock-meta"><span>Market ${s.trade_status}</span><span>Tick ${idr(s.tick_size)}</span><span>Liquidity ${s.liquidity.grade}</span><span>ADV ${s.liquidity.average_daily_value?idr(s.liquidity.average_daily_value):'DATA NOT AVAILABLE'}</span></div></div><div class="hero-number"><strong>${idr(s.last_price)}</strong><small class="${s.change_pct>=0?'positive':'negative'}">${pct(s.change_pct)}</small><em>${escapeHtml(s.market_data_as_of||'timestamp unavailable')}</em></div></header>
      <div class="quality-banner"><span>● ${s.data_quality.status} · confidence ${s.data_quality.confidence??'—'}% · ${escapeHtml(s.data_quality.source)}</span><span>Stored snapshot · no rescan · no provider request</span></div>
      <section class="score-grid"><div><small>ENGINE COMPOSITE</small><strong>${score.engine??'—'}<i>/100</i></strong></div><div><small>ARJUM SCORE</small><strong>${score.arjum??'—'}<i>/100</i></strong></div><div><small>TECHNICAL</small><strong>${escapeHtml(score.technical||'—')}</strong></div><div><small>BROKER FLOW</small><strong>${escapeHtml(score.broker_flow||'—')}</strong></div><div><small>FUNDAMENTAL</small><strong>${escapeHtml(score.fundamental||'—')}</strong></div><div><small>FINAL STATUS</small><strong class="positive">${escapeHtml(score.final_status||'—')}</strong></div></section>

      <article class="detail-panel chart-panel"><div class="panel-title-row"><div><p class="eyebrow">PRICE WORKSPACE</p><h2>Multi-timeframe chart</h2></div><div class="timeframe-tabs">${['1m','5m','15m','1H','Daily','Weekly'].map(x=>`<button class="${x===s.chart.default_timeframe?'active':''}" data-timeframe="${x}" ${asArray(s.chart.available_timeframes).includes(x)?'':'disabled'}>${x}</button>`).join('')}</div></div><div class="chart-legend"><span class="candle-up">OHLC</span><span class="ema">EMA20</span><span class="vwap">VWAP</span><span class="support">Support</span><span class="resistance">Resistance</span><span>Volume</span></div><div id="stockChartMount">${stockChart(s.chart,s.chart.default_timeframe)}</div><div id="candleInspector" class="candle-inspector"><span>Pilih atau arahkan pointer ke candle untuk melihat OHLCV.</span></div><div class="chart-help">Arahkan pointer, klik, atau gunakan Tab pada candle untuk melihat waktu dan nilai OHLCV.</div><div class="chart-plans">${asArray(s.agent_views).filter(v=>v.plan?.entry_low).map(v=>`<span><b>${v.agent_name}</b> ${idr(v.plan.entry_low)}–${idr(v.plan.entry_high)} · SL ${idr(v.plan.stop_price)} · TP ${asArray(v.plan.targets).map(idr).join('/')||'—'}</span>`).join('')||'No active plan overlays'}</div><div class="data-provenance">${s.chart.status} · ${s.chart.default_timeframe} · ${s.chart.series?.[s.chart.default_timeframe]?.length||0} cached candles · no provider request</div></article>

      <article class="detail-panel"><div class="panel-title-row"><div><p class="eyebrow">INDEPENDENT DESKS</p><h2>Pandangan & trading plan setiap agen</h2></div><span>Engine / Arjum / agent confidence dipisahkan</span></div><div class="agent-view-head"><span>Agent</span><span>Decision</span><span>Confidence</span><span>Status</span></div>${asArray(s.agent_views).map(renderPlan).join('')}</article>

      <div class="stock-columns"><section>
        <article class="detail-panel"><div class="panel-title-row"><div><p class="eyebrow">TECHNICAL</p><h2>Relevant indicators</h2></div><span>${tech.status}</span></div>${tech.status==='AVAILABLE'?`<div class="trend-row">${Object.entries(tech.trend||{}).map(([k,v])=>`<span><small>${k}</small><b>${shown(v)}</b></span>`).join('')}</div><div class="indicator-grid">${[['RSI',shown(tech.rsi)],['MACD',shown(tech.macd)],['ADX',shown(tech.adx)],['ATR',shown(tech.atr)],['Bollinger',shown(tech.bollinger)],['Relative volume',tech.relative_volume==null?'—':tech.relative_volume+'×'],['RS vs IHSG',tech.relative_strength_ihsg==null?'—':tech.relative_strength_ihsg+'%'],['RS vs sector',tech.relative_strength_sector==null?'—':tech.relative_strength_sector+'%'],['Swing high / low',tech.swing_high==null?'—':`${tech.swing_high} / ${tech.swing_low}`],['Gap',tech.gap==null?'—':tech.gap+'%'],['Pattern',shown(tech.candlestick)]].map(x=>`<span><small>${x[0]}</small><b>${escapeHtml(x[1])}</b></span>`).join('')}</div>`:unavailable()}</article>
        <article class="detail-panel"><div class="panel-title-row"><div><p class="eyebrow">BROKER & FOREIGN FLOW</p><h2>${flow.verdict||'Flow intelligence'}</h2></div><span>${flow.period||'—'}</span></div>${flow.status==='AVAILABLE'?`<div class="flow-summary"><span><small>NET BUY</small><b class="positive">${idr(flow.net_buy)}</b></span><span><small>FOREIGN NET</small><b class="positive">${idr(flow.foreign_net)}</b></span><span><small>CONSISTENCY</small><b>${flow.consistency}</b></span><span><small>SILENT ACCUM.</small><b>${flow.silent_accumulation?'YES':'NO'}</b></span></div><div class="broker-columns"><div><strong>Heavy buyers</strong>${asArray(flow.heavy_buyers).map(x=>`<span class="positive">${x}</span>`).join('')||'<span>—</span>'}</div><div><strong>Heavy sellers</strong>${asArray(flow.heavy_sellers).map(x=>`<span class="negative">${x}</span>`).join('')||'<span>—</span>'}</div></div><p class="method-note">Price/flow conflict: ${flow.price_flow_conflict?'DETECTED':'none detected'}.</p>`:unavailable()}</article>
        <article class="detail-panel arjum-panel"><div class="panel-title-row"><div><p class="eyebrow">ARJUM CACHE</p><h2>Independent cross-check</h2></div><span>${arjum.status} · ${arjum.as_of||'—'}</span></div>${arjum.status==='CACHED'?`<div class="indicator-grid">${[['Verdict',arjum.verdict],['Signal score',arjum.signal_score==null?'—':arjum.signal_score+'/100'],['Pivot support',(arjum.pivot_support||[]).map(idr).join(' · ')||'—'],['Pivot resistance',(arjum.pivot_resistance||[]).map(idr).join(' · ')||'—'],['Broker period',brokerPayload.broker_start_date&&brokerPayload.broker_end_date?`${brokerPayload.broker_start_date} – ${brokerPayload.broker_end_date}`:'—'],['Broker coverage',(brokerPayload.brokers||[]).length+' brokers'],['Accumulation buyers',(accumulationPayload.top_buyers||[]).length],['Seasonality years',(seasonalPayload.years||[]).length]].map(x=>`<span><small>${x[0]}</small><b>${escapeHtml(shown(x[1]))}</b></span>`).join('')}</div>${arjumReport(arjum.analysis_sections)}<div class="comparison-note"><b>Engine comparison</b>Skor Arjum dan keputusan tiap agen ditampilkan terpisah; cache ini tidak dipanggil ulang ketika halaman dibuka.</div>`:unavailable()}</article>
      </section><aside>
        <article class="detail-panel"><div class="panel-title-row"><div><p class="eyebrow">MASTER FUND</p><h2>Posisi lintas agen</h2></div><span>${s.positions.length} open</span></div>${s.positions.length?s.positions.map(p=>`<div class="position-card"><a href="/agents/${p.agent_id}">${escapeHtml(p.agent_name)}</a><b class="${p.pnl_pct>=0?'positive':'negative'}">${pct(p.pnl_pct)}</b><p>${p.lots} lot · ${idr(p.last_price*p.lots*100)} · risk ${idr(Math.max(0,(p.entry_price-(p.stop_price||p.entry_price))*p.lots*100))}</p></div>`).join(''):unavailable('NO OPEN POSITION')}<div class="portfolio-totals"><span><small>TOTAL EXPOSURE</small><b>${idr(s.portfolio.total_exposure)}</b></span><span><small>MASTER FUND</small><b>${s.portfolio.master_fund_pct}%</b></span><span><small>COMBINED RISK</small><b>${idr(s.portfolio.combined_risk)}</b></span><span><small>ORDER CONFLICT</small><b>${s.portfolio.order_conflicts.length||'NONE'}</b></span></div></article>
        <article class="detail-panel"><div class="panel-title-row"><div><p class="eyebrow">FUNDAMENTAL</p><h2>Company health</h2></div><span>${fund.quality_score==null?fund.status:`QUALITY ${fund.quality_score}/100`}</span></div>${fund.status==='AVAILABLE'?`<div class="fundamental-legend"><span class="fundamental-good">● Bagus</span><span class="fundamental-bad">● Perlu perhatian</span><span class="fundamental-neutral">● Netral</span></div><div class="indicator-grid fundamental-grid">${fundamentalMetrics.map(item=>`<span class="fundamental-card ${String(item.status||'UNAVAILABLE').toLowerCase()}"><small>${escapeHtml(item.label)}</small><b>${escapeHtml(fundamentalValue(item))}</b><em>${escapeHtml(item.status==='GOOD'?'BAGUS':item.status==='BAD'?'PERLU PERHATIAN':item.status==='NEUTRAL'?'NETRAL':'DATA NOT AVAILABLE')}${item.fallback?' · DATA LAMA':''}</em><i>${escapeHtml(item.period_end||fund.period_end||'—')}</i></span>`).join('')}</div><details class="fundamental-details"><summary>Lihat nilai laporan mentah</summary><div class="indicator-grid fundamental-grid">${[['Revenue',fund.revenue],['Operating income',fund.operating_income],['Net income',fund.net_income],['EPS',fund.eps],['Margin',fund.margin],['Dividend paid',fund.dividend]].map(([label,value])=>`<span><small>${label}</small><b>${value==null?'DATA NOT AVAILABLE':Math.abs(value)>=1000000?idr(value):escapeHtml(shown(value))}</b></span>`).join('')}</div></details><p class="method-note">${escapeHtml(fund.calculation_note||'Nilai yang tidak tersedia tidak diestimasi.')}</p><div class="data-provenance">${escapeHtml(fund.source||'stored fundamental snapshot')} · ${escapeHtml(asArray(fund.coverage).join(' · '))} · ${escapeHtml(fund.as_of||'—')}</div>`:unavailable()}</article>
        <article class="detail-panel"><p class="eyebrow">AUDIT TRAIL</p><h2>Riwayat keputusan</h2><div class="timeline">${s.decision_history.map(x=>`<div><time>${x.at.slice(5,16).replace('T',' ')}</time><span><b>${escapeHtml(x.agent_id)}</b>${escapeHtml(x.event)}</span><em>${x.kind}</em></div>`).join('')||unavailable('NO DECISION HISTORY')}</div></article>
        <article class="detail-panel"><p class="eyebrow">REPORT HISTORY</p><h2>Perubahan evaluasi</h2><div class="timeline report-timeline">${s.report_history.map(x=>`<a href="/reports/${x.report_date}"><time>${x.report_date}</time><span><b>${x.score}/100 · ${x.verdict}</b>${escapeHtml(x.change)}</span></a>`).join('')||unavailable('NO REPORT HISTORY')}</div></article>
      </aside></div>
      <div class="data-provenance">Snapshot ${escapeHtml(s.snapshot_version)} · source ${escapeHtml(s.source_mode)} · rescan=${s.rescan_triggered} · external requests=${s.external_requests_triggered}</div>`;
    bindStockChart(root,s,s.chart.default_timeframe);
    root.querySelectorAll('.timeframe-tabs button').forEach(btn=>btn.addEventListener('click',()=>{const timeframe=btn.dataset.timeframe;root.querySelectorAll('.timeframe-tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');root.querySelector('#stockChartMount').innerHTML=stockChart(s.chart,timeframe);root.querySelector('.chart-panel .data-provenance').textContent=`${s.chart.status} · ${timeframe} · ${s.chart.series?.[timeframe]?.length||0} cached candles · no provider request`;bindStockChart(root,s,timeframe)}));
  }catch(e){const title=e.status===404?'Saham tidak ditemukan':'Halaman saham gagal dirender';root.innerHTML=`<div class="error-state"><b>${title}</b><br>${escapeHtml(e.message)}</div>`}
}

async function renderReport(){const root=document.querySelector('#reportPage');if(!root)return;try{const reportDate=routeId('report');const r=await getJSON(reportDate?`/api/reports/${encodeURIComponent(reportDate)}`:'/api/reports/latest');const f=r.funnel;root.innerHTML=`<header class="detail-hero"><div><p class="eyebrow">PULSE DAILY EVALUATION</p><h1>${r.evaluation_date}</h1><p>Universe ${r.universe.type} · laporan dibentuk dari evaluasi tersimpan</p></div><div class="hero-number"><strong>${r.market_regime.label.replaceAll('_',' ')}</strong><small>Confidence ${r.market_regime.confidence}%</small></div></header><div class="quality-banner"><span>● ${r.status} · no rescan</span><span>${r.generated_at}</span></div><section class="detail-panel"><h2>Evaluation funnel</h2><div class="report-funnel"><div><b>${f.technical_matches}</b><small>TECHNICAL MATCH</small></div><div><b>${f.hard_rejects}</b><small>HARD REJECT</small></div><div><b>${f.shortlisted}</b><small>SHORTLISTED</small></div><div><b>${f.actionable}</b><small>ACTIONABLE</small></div><div><b>${f.silent_accumulation}</b><small>SILENT ACCUM.</small></div></div><div class="data-provenance">Source mode: ${r.source_mode} · rescan triggered: ${r.rescan_triggered}</div></section><section class="detail-panel"><h2>Top setup</h2>${r.setups.map(s=>`<div class="decision-card"><div class="decision-head"><a href="/stocks/${s.symbol}">${s.symbol}</a><span>${s.status}</span><span class="signal-badge buy">SCORE ${s.score}</span></div><div class="plan-strip"><span><small>ENTRY</small><b>${idr(s.entry_low)}–${idr(s.entry_high)}</b></span><span><small>STOP</small><b>${idr(s.stop_price)}</b></span><span><small>TARGET</small><b>${idr(s.target_price)}</b></span><span><small>EQUITY RISK</small><b>${s.agent_equity_risk_pct}%</b></span></div></div>`).join('')}</section>`}catch(e){root.innerHTML=`<div class="error-state">Laporan belum tersedia: ${escapeHtml(e.message)}. Tidak ada scan yang dijalankan.</div>`}}
renderAgent();renderStock();renderReport();
