import Link from 'next/link';
import { notFound } from 'next/navigation';
import { EquityChart } from '@/components/EquityChart';
import { getStockAgent, type Row } from '@/lib/stock-data';

export const dynamic = 'force-dynamic';
const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const num = new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 });
const n = (v: unknown) => Number(v ?? 0), s = (v: unknown) => String(v ?? '—');
const tone = (v: unknown) => n(v) > 0 ? 'text-positive' : n(v) < 0 ? 'text-negative' : 'text-ink-muted';

export default async function StockAgentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const agent = await getStockAgent(id);
  if (!agent) notFound();
  const agentRow = agent as Row;
  const performance = agent.performance;
  const strategy = agent.strategy;
  const positions = agent.positions;
  const orders = agent.pending_orders as Row[];
  const decisions = agent.decisions as Row[];
  const journal = agent.trade_journal as Row[];
  return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6">
    <div className="mb-5"><Link href="/saham#agents" className="font-mono text-xs text-accent hover:underline">← Semua agen</Link></div>
    <header className="mb-7 flex flex-col gap-4 rounded-2xl border border-border bg-surface p-6 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-wide text-emerald-400">{s(agentRow.validation_status)} · strategy v{s(agentRow.strategy_version)}</p><h1 className="mt-2 text-3xl font-semibold">{s(agentRow.name)}</h1><p className="mt-2 max-w-2xl text-sm text-ink-muted">{s(agentRow.description)} · keputusan, equity, dan ledger independen.</p></div><div className="md:text-right"><p className="font-mono text-2xl font-semibold">{idr.format(n(agentRow.equity))}</p><p className={`font-mono text-sm ${tone(agent.pnl_pct)}`}>{n(agent.pnl_pct) >= 0 ? '+' : ''}{num.format(n(agent.pnl_pct))}%</p></div></header>
    <section className="mb-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Net P/L', idr.format(performance.net_pnl)], ['Win rate', performance.win_rate == null ? 'N/A' : `${num.format(performance.win_rate)}%`], ['Profit factor', performance.profit_factor == null ? 'N/A' : num.format(performance.profit_factor)], ['Average R', performance.avg_r == null ? 'N/A' : `${num.format(performance.avg_r)}R`], ['Max drawdown', `${num.format(performance.max_drawdown_pct)}%`]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-surface p-4"><p className="font-mono text-[10px] uppercase text-ink-faint">{label}</p><p className="mt-2 font-mono text-lg font-semibold">{value}</p></div>)}</section>
    <section className="mb-7 rounded-xl border border-border bg-surface p-5"><div className="mb-3 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase text-emerald-400">Performance</p><h2 className="text-lg font-semibold">Equity curve</h2></div><span className="font-mono text-xs text-ink-faint">{(agent.equity_history as Row[]).length} snapshot</span></div><EquityChart rows={agent.equity_history as Row[]} /></section>
    <div className="mb-7 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-lg font-semibold">Open positions · {positions.length}</h2>{positions.length ? positions.map((p) => <Link href={`/saham/stocks/${p.symbol}`} key={p.id} className="mb-3 block rounded-lg border border-border bg-bg p-4 hover:border-emerald-500/50"><div className="flex justify-between"><b className="text-accent">{p.symbol} · {p.lots} lot</b><b className={tone(p.unrealized_pnl)}>{idr.format(p.unrealized_pnl)}</b></div><p className="mt-2 font-mono text-xs text-ink-muted">Nilai {idr.format(p.market_value)} · entry {idr.format(p.entry_price)} · last {idr.format(p.last_price)}</p></Link>) : <p className="text-sm text-ink-faint">Agen sedang flat.</p>}</section>
      <section className="rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-lg font-semibold">Pending orders · {orders.length}</h2>{orders.length ? orders.map((o) => <div key={s(o.id)} className="mb-3 rounded-lg border border-border bg-bg p-4"><div className="flex justify-between"><Link href={`/saham/stocks/${s(o.symbol)}`} className="font-semibold text-accent">{s(o.symbol)}</Link><span className="font-mono text-xs text-warning">{s(o.status)}</span></div><p className="mt-2 font-mono text-xs text-ink-muted">{n(o.lots)} lot · limit {idr.format(n(o.limit_price))} · SL {idr.format(n(o.stop_price))} · TP {idr.format(n(o.target_price))}</p></div>) : <p className="text-sm text-ink-faint">Tidak ada order menunggu.</p>}</section></div>
    {strategy ? <section className="mb-7 rounded-xl border border-border bg-surface p-5"><p className="font-mono text-[10px] uppercase text-emerald-400">Strategy playbook</p><h2 className="mt-1 text-xl font-semibold">{strategy.objective}</h2><p className="mt-2 font-mono text-xs text-ink-muted">Timeframe: {strategy.timeframes}</p><div className="mt-5 grid gap-5 md:grid-cols-3">{[['Aturan entry', strategy.entry_rules], ['Aturan exit', strategy.exit_rules], ['No trade', strategy.no_trade]].map(([title, values]) => <div key={title as string}><h3 className="mb-2 font-semibold">{title as string}</h3><ul className="space-y-2 text-sm text-ink-muted">{(values as string[]).map((value) => <li key={value}>• {value}</li>)}</ul></div>)}</div></section> : null}
    <section className="mb-7 rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-lg font-semibold">Latest evaluations</h2><div className="space-y-3">{decisions.slice(0, 25).map((d) => <article key={s(d.id)} className="rounded-lg border border-border bg-bg p-4"><div className="flex flex-wrap items-center gap-3"><Link href={`/saham/stocks/${s(d.symbol)}`} className="font-semibold text-accent">{s(d.symbol)}</Link><span className="text-sm text-ink-muted">{s(d.name)}</span><span className="ml-auto rounded-full border border-border px-2 py-1 font-mono text-[10px]">{s(d.action)} · {s(d.confidence)}</span></div><p className="mt-2 text-sm text-ink-muted">{s(d.rationale)}</p><p className="mt-2 font-mono text-xs text-ink-faint">Entry {d.entry_low == null ? '—' : idr.format(n(d.entry_low))} · Stop {d.stop_price == null ? '—' : idr.format(n(d.stop_price))} · Target {d.target_price == null ? '—' : idr.format(n(d.target_price))}</p></article>)}</div></section>
    <section className="rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-lg font-semibold">Trade journal</h2><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left font-mono text-xs"><thead className="border-b border-border text-[10px] uppercase text-ink-faint"><tr><th className="py-2">Ticker</th><th>Dibuka</th><th>Ditutup</th><th>Lot</th><th>Entry</th><th>Exit</th><th>Net result</th><th>R</th><th>Alasan exit</th></tr></thead><tbody>{journal.map((t) => <tr key={s(t.id)} className="border-b border-border/60 text-ink-muted"><td className="py-3"><Link className="text-accent" href={`/saham/stocks/${s(t.symbol)}`}>{s(t.symbol)}</Link></td><td>{s(t.opened_at).slice(0, 16).replace('T', ' ')}</td><td>{t.closed_at ? s(t.closed_at).slice(0, 16).replace('T', ' ') : 'OPEN'}</td><td>{s(t.lots)}</td><td>{idr.format(n(t.entry_price))}</td><td>{t.exit_price == null ? '—' : idr.format(n(t.exit_price))}</td><td className={tone(t.net_pnl)}>{t.net_pnl == null ? '—' : idr.format(n(t.net_pnl))}</td><td>{t.r_multiple == null ? '—' : `${num.format(n(t.r_multiple))}R`}</td><td>{s(t.exit_reason)}</td></tr>)}</tbody></table></div></section>
  </main>;
}
