import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getStockWorkspace, type Row } from '@/lib/stock-data';
import { StockPriceChart, type ChartLevel } from '@/components/StockPriceChart';

export const dynamic = 'force-dynamic';
const idr = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 });
const num = new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 });
const n = (v: unknown) => Number(v ?? 0), s = (v: unknown) => String(v ?? '—');
const tone = (v: unknown) => n(v) > 0 ? 'text-positive' : n(v) < 0 ? 'text-negative' : 'text-ink-muted';
const value = (v: unknown, unit?: unknown) => v == null ? 'DATA NOT AVAILABLE' : unit === 'IDR' ? idr.format(n(v)) : `${num.format(n(v))}${unit === '%' ? '%' : unit === '×' ? '×' : ''}`;

export default async function StockPage({ params }: { params: Promise<{ symbol: string }> }) {
  const { symbol } = await params;
  const data = await getStockWorkspace(symbol);
  if (!data) notFound();
  const stock = data.instrument, flow = data.flow, fundamental = data.fundamental;
  const indicators = Array.isArray(fundamental?.indicators) ? fundamental.indicators as Row[] : [];
  const chartLevels: ChartLevel[] = [
    ...data.positions.flatMap((position) => [
      { label: `${position.agent_name} entry`, value: position.entry_price, tone: 'entry' as const },
      ...(position.stop_price ? [{ label: `${position.agent_name} stop`, value: position.stop_price, tone: 'stop' as const }] : []),
      ...(position.target_price ? [{ label: `${position.agent_name} target`, value: position.target_price, tone: 'target' as const }] : []),
    ]),
    ...data.views.flatMap((view) => {
      const plan = view.plan as Row | null;
      if (!plan) return [];
      return [
        ...(n(plan.entry_low) > 0 ? [{ label: `${view.agent_name} entry`, value: n(plan.entry_low), tone: 'entry' as const }] : []),
        ...(n(plan.stop_price) > 0 ? [{ label: `${view.agent_name} stop`, value: n(plan.stop_price), tone: 'stop' as const }] : []),
        ...(n(plan.target_price) > 0 ? [{ label: `${view.agent_name} target`, value: n(plan.target_price), tone: 'target' as const }] : []),
      ];
    }),
  ];
  return <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6">
    <div className="mb-5"><Link href="/saham#screener" className="font-mono text-xs text-accent hover:underline">← Screener seluruh IDX</Link></div>
    <header className="mb-4 flex flex-col gap-4 rounded-2xl border border-border bg-surface p-6 md:flex-row md:items-end md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-wide text-emerald-400">{s(stock.sector)} · {s(stock.subsector)}</p><h1 className="mt-2 text-3xl font-semibold">{s(stock.symbol)} <span className="text-lg font-normal text-ink-muted">{s(stock.name)}</span></h1><p className="mt-2 font-mono text-xs text-ink-faint">Stored snapshot · diperbarui {s(stock.market_data_as_of)} · halaman ini tidak memanggil provider</p></div><div className="md:text-right"><p className="font-mono text-3xl font-semibold">{stock.last_price == null ? '—' : idr.format(n(stock.last_price))}</p><p className={`font-mono text-sm ${tone(stock.change_pct)}`}>{stock.change_pct == null ? '—' : `${n(stock.change_pct) >= 0 ? '+' : ''}${num.format(n(stock.change_pct))}%`}</p></div></header>
    <section className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Engine score', stock.evaluation_score == null ? '—' : `${s(stock.evaluation_score)}/100`], ['Final status', s(stock.evaluation_status)], ['Broker flow', flow?.status === 'AVAILABLE' ? s(flow.verdict) : 'DATA NOT AVAILABLE'], ['Fundamental', fundamental?.status === 'AVAILABLE' ? `Quality ${s(fundamental.quality_score)}` : 'DATA NOT AVAILABLE'], ['Data source', 'Stored evaluation']].map(([label, val]) => <div key={label} className="rounded-xl border border-border bg-surface p-4"><p className="font-mono text-[10px] uppercase text-ink-faint">{label}</p><p className="mt-2 text-sm font-semibold">{val}</p></div>)}</section>
    <section className="mb-6 rounded-xl border border-border bg-surface p-5"><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><p className="font-mono text-[10px] uppercase text-emerald-400">Stored OHLCV · no page-load API call</p><h2 className="text-xl font-semibold">Chart multi-timeframe</h2></div><span className={`rounded-full border px-3 py-1 font-mono text-[10px] ${data.chart ? 'border-positive/40 text-positive' : 'border-warning/40 text-warning'}`}>{data.chart ? 'CACHED' : 'WAITING COLLECTOR'}</span></div><StockPriceChart snapshot={data.chart} levels={chartLevels}/></section>
    <section className="mb-6 rounded-xl border border-border bg-surface p-5"><div className="mb-4"><p className="font-mono text-[10px] uppercase text-emerald-400">Independent desks</p><h2 className="text-xl font-semibold">Pandangan dan trading plan setiap agen</h2></div><div className="space-y-3">{data.views.map((view) => { const plan = view.plan as Row | null; return <details key={view.agent_id} className="group rounded-xl border border-border bg-bg p-4"><summary className="flex cursor-pointer list-none flex-wrap items-center gap-3"><Link href={`/saham/agents/${view.agent_id}`} className="font-semibold text-accent">{view.agent_name}</Link><span className="text-xs text-ink-muted">{view.horizon}</span><span className="ml-auto rounded-full border border-border px-2 py-1 font-mono text-[10px]">{view.action}</span><span className="font-mono text-xs">{view.confidence == null ? '—' : `${s(view.confidence)}%`}</span><span className="font-mono text-[10px] text-ink-faint">{view.status}</span></summary><div className="mt-4 border-t border-border pt-4"><p className="text-sm text-ink-muted">{view.rationale}</p>{plan ? <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[['Entry', plan.entry_low == null ? '—' : `${idr.format(n(plan.entry_low))}–${idr.format(n(plan.entry_high))}`], ['Stop', plan.stop_price == null ? '—' : idr.format(n(plan.stop_price))], ['Target', plan.target_price == null ? '—' : idr.format(n(plan.target_price))], ['R/R', plan.risk_reward == null ? '—' : num.format(n(plan.risk_reward))], ['Risk equity', plan.equity_risk_pct == null ? '—' : `${num.format(n(plan.equity_risk_pct))}%`], ['Lot', plan.lots == null ? '—' : s(plan.lots)]].map(([label, val]) => <div key={label}><p className="font-mono text-[10px] uppercase text-ink-faint">{label}</p><p className="mt-1 font-mono text-xs text-ink">{val}</p></div>)}</div> : null}</div></details>; })}</div></section>
    <div className="mb-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-5"><div className="mb-4 flex justify-between"><div><p className="font-mono text-[10px] uppercase text-emerald-400">Fundamental</p><h2 className="text-xl font-semibold">Company health</h2></div><span className="font-mono text-xs text-ink-muted">{fundamental?.status === 'AVAILABLE' ? `Quality ${s(fundamental.quality_score)}/100` : 'DATA NOT AVAILABLE'}</span></div>{indicators.length ? <div className="grid gap-3 sm:grid-cols-2">{indicators.map((item) => <div key={s(item.key)} className={`rounded-lg border p-3 ${item.status === 'GOOD' ? 'border-positive/30 bg-positive-bg' : item.status === 'BAD' ? 'border-negative/30 bg-negative-bg' : 'border-border bg-bg'}`}><p className="text-xs text-ink-muted">{s(item.label)}</p><p className="mt-1 font-mono text-sm font-semibold">{value(item.value, item.unit)}</p><p className={`mt-1 font-mono text-[10px] ${item.status === 'GOOD' ? 'text-positive' : item.status === 'BAD' ? 'text-negative' : 'text-ink-faint'}`}>{item.status === 'GOOD' ? 'BAGUS' : item.status === 'BAD' ? 'PERLU PERHATIAN' : s(item.status)} · {s(item.period_end)}</p></div>)}</div> : <p className="text-sm text-ink-faint">DATA NOT AVAILABLE — tidak ada estimasi buatan.</p>}</section>
      <section className="rounded-xl border border-border bg-surface p-5"><div className="mb-4"><p className="font-mono text-[10px] uppercase text-emerald-400">Broker & foreign flow</p><h2 className="text-xl font-semibold">{flow?.status === 'AVAILABLE' ? s(flow.verdict) : 'DATA NOT AVAILABLE'}</h2></div>{flow?.status === 'AVAILABLE' ? <div className="grid gap-3 sm:grid-cols-2">{[['Net buy/sell', idr.format(n(flow.net_buy))], ['Foreign net', idr.format(n(flow.foreign_net))], ['Consistency', s(flow.consistency)], ['As of', s(flow.source_fetched_at)]].map(([label, val]) => <div key={label} className="rounded-lg border border-border bg-bg p-3"><p className="font-mono text-[10px] uppercase text-ink-faint">{label}</p><p className="mt-1 font-mono text-sm">{val}</p></div>)}</div> : <p className="text-sm text-ink-faint">Arjum flow belum tersedia pada snapshot ini.</p>}</section></div>
    <section className="mb-6 rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-xl font-semibold">Posisi lintas agen · {data.positions.length}</h2>{data.positions.length ? <div className="grid gap-3 md:grid-cols-2">{data.positions.map((p) => <Link key={p.id} href={`/saham/agents/${p.agent_id}`} className="rounded-lg border border-border bg-bg p-4 hover:border-emerald-500/50"><div className="flex justify-between"><b>{p.agent_name} · {p.lots} lot</b><span className={tone(p.pnl_pct)}>{p.pnl_pct >= 0 ? '+' : ''}{num.format(p.pnl_pct)}%</span></div><p className="mt-2 font-mono text-xs text-ink-muted">Eksposur {idr.format(p.market_value)} · risk ke stop {idr.format(Math.max(0, (p.entry_price - n(p.stop_price)) * p.lots * 100))}</p></Link>)}</div> : <p className="text-sm text-ink-faint">Tidak ada posisi terbuka pada ticker ini.</p>}</section>
    <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-xl font-semibold">Riwayat keputusan</h2><div className="space-y-3">{data.decisions.slice(0, 30).map((d) => <div key={s(d.id)} className="border-l border-border pl-4"><p className="font-mono text-[10px] text-ink-faint">{s(d.evaluated_at)}</p><p className="text-sm"><Link className="text-accent" href={`/saham/agents/${s(d.agent_id)}`}>{s(d.agent_id)}</Link> · {s(d.action)} · {s(d.status)}</p><p className="text-xs text-ink-muted">{s(d.rationale)}</p></div>)}</div></section><section className="rounded-xl border border-border bg-surface p-5"><h2 className="mb-4 text-xl font-semibold">Riwayat daily report</h2>{data.reports.length ? <div className="space-y-3">{data.reports.map((r) => <Link key={s(r['report_date'])} href={`/saham/reports/${s(r['report_date'])}`} className="block rounded-lg border border-border bg-bg p-4 hover:border-emerald-500/50"><div className="flex justify-between"><b>{s(r['report_date'])}</b><span className="font-mono text-xs">Score {s(r['score'])}</span></div><p className="mt-1 text-xs text-ink-muted">{s(r['action'])} · {s(r['status'])} · {s(r['rationale'])}</p></Link>)}</div> : <p className="text-sm text-ink-faint">Ticker belum masuk rekomendasi daily report tersimpan.</p>}</section></div>
  </main>;
}
